import os

FIREBASE_API_KEY = os.getenv('FIREBASE_API_KEY')
YELP_API_KEY = os.getenv('YELP_API_KEY')
TICKETMASTER_API_KEY = os.getenv('TICKETMASTER_API_KEY')
CLEARDB_PARAMETERS = os.getenv('CLEARDB_PARAMETERS')
#FIREBASE_CONFIG = os.getenv('FIREBASE_CONFIG')
FIREBASE_CONFIG_PRIVATE_KEY = os.getenv('FIREBASE_CONFIG_PRIVATE_KEY')
FIREBASE_CONFIG_CLIENT_EMAIL = os.getenv('FIREBASE_CONFIG_CLIENT_EMAIL')
FIREBASE_CONFIG_TOKEN_URI = os.getenv('FIREBASE_CONFIG_TOKEN_URI')
FIREBASE_CONFIG_PROJECT_ID = os.getenv('FIREBASE_CONFIG_PROJECT_ID')