import os

FIREBASE_API_KEY = os.getenv('FIREBASE_API_KEY')
YELP_API_KEY = os.getenv('YELP_API_KEY')
TICKETMASTER_API_KEY = os.getenv('TICKETMASTER_API_KEY')
CLEARDB_PARAMETERS = os.getenv('CLEARDB_PARAMETERS')